apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vwire.fullname" . }}
  labels:
    {{- include "vwire.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vwire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vwire.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vwire.serviceAccountName" . }}
      hostNetwork: {{ .Values.network.hostNetwork }}
      hostPID: {{ .Values.network.hostPID }}
      dnsPolicy: {{ .Values.network.dnsPolicy }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VWIRE_INTERFACE
              value: {{ .Values.config.interface | quote }}
            - name: VWIRE_XDP_MODE
              value: {{ .Values.config.xdpMode | quote }}
            - name: VWURE_HTTPS
              value: {{ .Values.config.enableHTTPS | quote }}
            - name: RUST_LOG
              value: {{ .Values.config.logLevel | quote }}
            {{- if .Values.config.backendAddress }}
            - name: VWIRE_BACKEND
              value: {{ .Values.config.backendAddress | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
            - name: dashboard
              containerPort: {{ .Values.service.dashboardPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
